### ISSUE TITLE
st7789: name 'lv' isn't defined?

### ISSUE THREAD

**Issue by dcmcshan** [lvgl-micropython/lvgl_micropython#155]
Running on M5 Atom S3:
`
python3 make.py esp32 clean BOARD=ESP32_GENERIC_S3 --flash-size=8 DISPLAY=ST7789 --usb-otg --dual-core-threads --ota`

Needs an import lvgl as lv.

```
LVGL MicroPython 1.23.0 on 2024-10-18; Generic ESP32S3 module with ESP32S3
Type "help()" for more information.
>>> import lvgl as lv
>>> import st7789
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "st7789.py", line 21, in <module>
  File "st7789.py", line 45, in ST7789
NameError: name 'lv' isn't defined
>>> 
```

**Comment by kdschlosser** [comment]
oh you are correct it does....

It is fixed....
