### ISSUE TITLE
ST7701 spi_3wire init crash

### ISSUE THREAD

**Issue by VsevolodVasin** [lvgl-micropython/lvgl_micropython#225]
**Describe the bug**

I'm trying to launch viewesmart display with lvgl. https://github.com/VIEWESMART/Product-Specification-and-Schematic/blob/main/ESP32/4.0inch/UEDX48480040E-WB-A%20SPEC.pdf

esp-idf working code - https://github.com/VIEWESMART/ESP32-IDF/tree/main/examples/4.0inch/UEDX48480040E-WB-3touch-SDK

An error occurs when trying to create the ST7701 class when initializing spi_3wire.

**If your problem is running the binding please past the code you are using below.**

```python
from micropython import const  # NOQA
import lcd_bus  # NOQA
import random  # For random number generation
import time  # For time management
import task_handler  # For task handling module
import spi3wire

_WIDTH = const(480)
_HEIGHT = const(480)

rgb_bus = lcd_bus.RGBBus(
        hsync = 16,
        vsync = 17,
        de= 18,
        pclk = 21,
        data0 = 4,
        data1 = 3,
        data2 = 2,
        data3 = 1,
        data4 = 0,
        data5 = 10,
        data6 = 9,
        data7 = 8,
        data8 = 7,
        data9 = 6,
        data10 = 5,
        data11 = 15,
        data12 = 14,
        data13 = 13,
        data14 = 12,
        data15 = 11,
        freq=16 * 1000 * 1000,
        
    )

spi_3wire = spi3wire.Spi3Wire(
     miso=47, sck=48, cs=39, cs_active_high=False
)
import lvgl as lv
import st7701

_BUF1 = rgb_bus.allocate_framebuffer(_WIDTH * _HEIGHT * 3, lcd_bus.MEMORY_SPIRAM)

_BUF2 = rgb_bus.allocate_framebuffer(_WIDTH * _HEIGHT * 3, lcd_bus.MEMORY_SPIRAM)
display = st7701.ST7701(data_bus=rgb_bus, display_width=_WIDTH,spi_3wire=spi_3wire, display_height=_HEIGHT,
                                              frame_buffer1=_BUF1, frame_buffer2=_BUF2, backlight_pin=38,
                                              color_space=lv.COLOR_FORMAT.RGB565, bus_shared_pins=False)
display.set_power(True)
display.init()
display.set_backlight(100)


scrn = lv.screen_active()
scrn.set_style_bg_color(lv.color_hex(0x000000), 0)

slider = lv.slider(scrn)
slider.set_size(300, 50)
slider.center()

label = lv.label(scrn)
label.set_text('HELLO WORLD!')
label.align(lv.ALIGN.CENTER, 0, -50)

import task_handler
th = task_handler.TaskHandler()

```

**My firmware setup**
```shell
 python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=st7701 INDEV=FT6x36
```

**Error:**

```shell
MPY: soft reboot
Traceback (most recent call last):
  File "<stdin>", line 49, in <module>
  File "rgb_display_framework.py", line 83, in init
  File "st7701.py", line 214, in _spi_3wire_init
TypeError: unsupported types for __lt__: 'NoneType', 'int'
```

**Comment by kdschlosser** [comment]
OK so there are a couple of issues with your code.

```python
from micropython import const
import lcd_bus  # NOQA
import spi3wire  # NOQA


_WIDTH = const(480)
_HEIGHT = const(480)

rgb_bus = lcd_bus.RGBBus(
    hsync=16,
    vsync=17,
    de=18,
    pclk=21,
    data0=4,
    data1=3,
    data2=2,
    data3=1,
    data4=0,
    data5=10,
    data6=9,
    data7=8,
    data8=7,
    data9=6,
    data10=5,
    data11=15,
    data12=14,
    data13=13,
    data14=12,
    data15=11,
    freq=13000000,

)

spi_3wire = spi3wire.Spi3Wire(
    miso=47, sck=48, cs=39, cs_active_high=False
)
import lvgl as lv
import st7701

# Times 2 because you are using RGB565 which is 2 bytes per pixel
# The RGB Bus driver has been updated so it is able to use 4 frame buffers.
# This allows LVGL to render only the parts that are actually getting updated
# and the rendering takes place to the much faster internal memory.
_BUF1 = rgb_bus.allocate_framebuffer(int(_WIDTH * _HEIGHT * 2 / 10), lcd_bus.MEMORY_INTERNAL)
_BUF2 = rgb_bus.allocate_framebuffer(int(_WIDTH * _HEIGHT * 2 / 10), lcd_bus.MEMORY_INTERNAL)


display = st7701.ST7701(
    data_bus=rgb_bus,
    display_width=_WIDTH,
    spi_3wire=spi_3wire,
    display_height=_HEIGHT,
    frame_buffer1=_BUF1,
    frame_buffer2=_BUF2,
    backlight_pin=38,
    color_space=lv.COLOR_FORMAT.RGB565,
    bus_shared_pins=False
)

display.set_power(True)
display.init(1)  # <=== THIS IS WHERE THE PROBLEM IS
# There are 16 different "types" for this display. So you need to choose 
# the correct one. for your display to work. use the numbers 1 to 16 when
# calling the init method until you fing the one that displays correctly for 
# your display 

display.set_backlight(100)

scrn = lv.screen_active()
scrn.set_style_bg_color(lv.color_hex(0x000000), 0)

slider = lv.slider(scrn)
slider.set_size(300, 50)
slider.center()

label = lv.label(scrn)
label.set_text('HELLO WORLD!')
label.align(lv.ALIGN.CENTER, 0, -50)

import task_handler  # NOQA

th = task_handler.TaskHandler()
```
